### ISSUE TITLE
Does ROCr support GUI-based software applications officially or not?

### ISSUE THREAD

**Issue by KristijanZic** [ROCm/ROCR-Runtime#116] opened 2021-03-01 18:56 UTC
In light of the new direction AMD is taking in regards to OpenCL support for graphical use cases with https://github.com/RadeonOpenCompute/ROCm/commit/6fb55e6f459ca2bcddba6c9b7ac39345fa7a51b7

It's important for us to know how this affects ROCr? Does ROCr now officially not support the GUI-based software applications use case?

**Comment by skeelyamd** [comment] 2021-03-01 19:10
No, ROCr works with GUI applications and so does OpenCL.  The RadeonPro Linux OpenCL is also (along with ROCm OCL) ROCr based and many GUI applications are known important supported apps.

**Comment by KristijanZic** [comment] 2021-03-01 19:18
Is there an official support? It seems to me if ROCm does not support it so doesn't the RadeonPro. They are both,as you said, ROCr based. 
If this is not correct then maybe AMD jumped the gun with the RadeonOpenCompute/ROCm@6fb55e6 ?

**Comment by johnbridgman** [comment] 2021-03-01 20:18
Not sure I understand the question. This is not a new direction, and is not a change. The ROCm **stack** has never included graphics userspace components (eg Mesa) and ROCm releases have never gone through graphics testing. 

That said, there is nothing in the ROCm components preventing use with graphical apps - the messaging applies to the ROCm **stack** as published in Github, not to the individual **components**. 

Our direction is towards more integration of graphics and compute, not less. The message only documents the current state, which has also been the state of the stack from the start (ie years). 

It does seem that we need to revisit the message, since it is definitely being interpreted differently from the way it was intended.

**Comment by schung-amd** [comment] 2024-10-29 14:29
Hi, closing this off as we've since revised the messaging here. The guidance given by @johnbridgman is still accurate. There are a couple of things to consider for graphical workloads, including GUI-based applications. 

- The main ROCm releases are intended primarily for headless configurations, and technically graphical workloads are not supported; that being said, all this lack of support means is that we are not comprehensively testing these ROCm releases with graphical workloads and functionality is not guaranteed.
- We have a release channel for ROCm versions specifically supporting graphical workloads: https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/native_linux/install-radeon.html
- For users who want to use current ROCm versions, `amdgpu-install` has `multimedia`, `multimediasdk`, and `graphics` usecases which install some of the userspace components required for graphical workloads such as `mesa`; see https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/amdgpu-install.html for more details.
- In terms of individual ROCm components such as ROCr, you shouldn't have to worry about this unless specifically noted in the component documentation.

**Closed by schung-amd** 2024-10-29 14:29 UTC
